name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one line script
        run: echo "Hello, World!"

      - name: Run a multiline script
        run: |
          echo "This is a multiline script"
          echo "It can contain multiple commands"
          echo "Each command will be executed in sequence"

  build-api:
    runs-on: windows-latest
    steps:
      - name: Build API
        run: echo "Building api"

  build-db:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Build DB
        run: echo "Building the database"

  packaging:
    needs: [build, build-db]
    runs-on: macos-latest
    steps:
      - name: Package App
        run: echo "Packaging the application"
